const STORE='opportunity_lab_v1';
const steps=[
{id:'trend',title:'Spot a trend',short:'What is changing?',goal:'Identify a meaningful structural change worth exploring.',do:'State the change clearly and record why you believe it is real.',dont:'Do not jump to a product or customer yet.',done:'You can explain the trend clearly and point to credible signals.'},
{id:'consequences',title:'Map consequences',short:'What does it cause?',goal:'Trace direct and second-order effects of the trend.',do:'Build simple cause → effect chains and note uncertainty.',dont:'Do not assume every consequence is a business opportunity.',done:'You have at least 3 plausible consequence chains.'},
{id:'actors',title:'Identify actors',short:'Who is affected?',goal:'Map who gains, loses, pays, decides, or gets extra work.',do:'List concrete actor groups and how the trend changes their world.',dont:'Do not choose your customer too early.',done:'You have several affected actors and a reason each matters.'},
{id:'evidence',title:'Collect evidence',short:'What is actually happening?',goal:'Gather raw real-world signals before interpreting them.',do:'Capture reports, complaints, reviews, discussions, search behavior, and observed actions.',dont:'Do not turn guesses into facts.',done:'You have enough independent signals to see repeated themes.'},
{id:'problems',title:'Discover problems',short:'Where is the friction?',goal:'Turn repeated evidence into clear problem statements.',do:'Cluster bottlenecks, costs, risks, frustrations, and poor workarounds.',dont:'Do not write solutions disguised as problems.',done:'You can rank a few evidence-backed problems.'},
{id:'customers',title:'Understand customers',short:'How do they solve it now?',goal:'Understand the strongest actor/problem combinations deeply.',do:'Ask about past behavior, urgency, alternatives, time, money, and existing spend.',dont:'Avoid “Would you use my app?”',done:'You know what people actually do today and what the problem costs them.'},
{id:'opportunity',title:'Choose opportunity',short:'Which problem deserves a test?',goal:'Select one problem based on evidence, not excitement.',do:'Compare pain, frequency, money at stake, alternatives, and reachability.',dont:'Do not pick the most technically interesting idea by default.',done:'One problem clearly deserves the next experiment.'},
{id:'test',title:'Test hypothesis',short:'Will behavior support it?',goal:'Run the smallest experiment that could falsify the opportunity.',do:'Test real behavior—preferably payment—with a manually deliverable offer.',dont:'Do not build the platform first.',done:'You have a measurable result against a pre-set threshold.'},
{id:'decide',title:'Decide',short:'Continue, narrow, retest, or stop?',goal:'Make one evidence-based decision and define the next move.',do:'Separate what you learned from what you hoped would happen.',dont:'Do not continue because of sunk cost.',done:'You know exactly what happens next—and why.'}
];
let state={version:3,cases:{},activeCaseId:null},currentStep=0;
const today=()=>new Date().toISOString().slice(0,10);
function blankCase(id,title='New research case',createdAt=today()){return {id,title,createdAt,updatedAt:createdAt,status:'Exploring',trend:{statement:'',signals:'',whyNow:''},consequences:[],actors:[],evidence:[],problems:[],interviews:[],hypothesis:{customer:'',problem:'',alternative:'',outcome:'',belief:'',threshold:'',assumption:''},tests:[],review:{evidence:'',surprise:'',behavior:'',dontBuild:'',asset:'',decision:'',next:''},aiNotes:''}}
function normalizeCase(c,id){const b=blankCase(id,c?.title||c?.projectName||c?.customerGroup||'Untitled research',c?.createdAt||today());c=Object.assign({},b,c||{});c.id=id;c.title=c.title||c.projectName||c.customerGroup||c.trend?.statement||'Untitled research';c.trend=Object.assign({},b.trend,c.trend||{});c.consequences=Array.isArray(c.consequences)?c.consequences:[];c.actors=Array.isArray(c.actors)?c.actors:[];c.evidence=Array.isArray(c.evidence)?c.evidence:[];c.problems=Array.isArray(c.problems)?c.problems:[];c.interviews=Array.isArray(c.interviews)?c.interviews:[];c.hypothesis=Object.assign({},b.hypothesis,c.hypothesis||{});c.tests=Array.isArray(c.tests)?c.tests:[];c.review=Object.assign({},b.review,c.review||{});c.status=c.review.decision?'Decided':c.tests.length?'Testing':'Exploring';return c}
function migrate(raw){if(raw?.version>=3&&raw.cases){Object.keys(raw.cases).forEach(id=>raw.cases[id]=normalizeCase(raw.cases[id],id));return raw}const next={version:3,cases:{},activeCaseId:null};if(raw?.weeks){Object.keys(raw.weeks).sort().forEach((week,i)=>{const old=raw.weeks[week]||{};const id='legacy_'+week.replaceAll('-','');const c=blankCase(id,old.projectName||old.customerGroup||old.trend?.statement||`Research ${week}`,week);Object.assign(c,{trend:old.trend||c.trend,consequences:old.consequences||[],actors:old.actors||[],evidence:old.evidence||[],problems:old.problems||[],interviews:old.interviews||[],hypothesis:old.hypothesis||c.hypothesis,tests:old.tests||[],review:old.review||c.review,aiNotes:old.aiNotes||''});next.cases[id]=normalizeCase(c,id);next.activeCaseId=id})}return next}
function load(){let raw={};try{raw=JSON.parse(localStorage.getItem(STORE))||{}}catch(e){}state=migrate(raw);if(!Object.keys(state.cases).length){const id='case_'+Date.now();state.cases[id]=blankCase(id,'Finland data-center expansion');state.activeCaseId=id}if(!state.activeCaseId||!state.cases[state.activeCaseId])state.activeCaseId=Object.keys(state.cases)[0];persist();renderHome()}
function persist(){const c=C();if(c){c.updatedAt=today();c.status=c.review.decision?'Decided':c.tests.length?'Testing':'Exploring'}localStorage.setItem(STORE,JSON.stringify(state));renderProgress()}
function C(){return state.cases[state.activeCaseId]}
function newCase(){const title=(prompt('Name this research case:','')||'').trim();if(!title)return;const id='case_'+Date.now();state.cases[id]=blankCase(id,title);state.activeCaseId=id;persist();goHome()}
function saveCaseMeta(){C().title=val('caseTitle')||'Untitled research';persist()}
function stepDoneFor(c,id){if(id==='trend')return !!c.trend.statement.trim();if(id==='consequences')return c.consequences.length>=3;if(id==='actors')return c.actors.length>=3;if(id==='evidence')return c.evidence.length>=5;if(id==='problems')return c.problems.length>=3;if(id==='customers')return c.interviews.length>=3;if(id==='opportunity')return !!(c.hypothesis.customer&&c.hypothesis.problem);if(id==='test')return c.tests.length>=1;if(id==='decide')return !!c.review.decision;return false}
function stepDone(id){return stepDoneFor(C(),id)}
function renderHome(){hideAll();show('overview');setVal('caseTitle',C().title);text('caseStarted',C().createdAt);text('caseStatus',C().status);document.getElementById('caseStatus').className='case-status '+C().status;document.getElementById('flow').innerHTML=steps.map((s,i)=>`<button class="step-card ${stepDone(s.id)?'done':''}" onclick="openStep(${i})"><span class="status">${stepDone(s.id)?'Done':'Open'}</span><div class="step-num">STEP ${i+1}</div><h3>${s.title}</h3><p>${s.short}</p></button>`).join('');renderProgress()}
function renderProgress(){const bar=document.getElementById('progressBar');if(!bar)return;const n=steps.filter(s=>stepDone(s.id)).length;bar.style.width=(n/steps.length*100)+'%';text('progressText',`${n} / ${steps.length}`)}
function hideAll(){['overview','detail','logView'].forEach(id=>document.getElementById(id)?.classList.add('hidden'))}
function show(id){document.getElementById(id)?.classList.remove('hidden')}
function goHome(){renderHome()}
function openStep(i){currentStep=i;hideAll();show('detail');renderStep()}
function moveStep(d){const n=currentStep+d;if(n<0||n>=steps.length)return;currentStep=n;renderStep();window.scrollTo({top:0,behavior:'smooth'})}
function renderStep(){const s=steps[currentStep];text('stepEyebrow',`Step ${currentStep+1} of ${steps.length}`);text('stepTitle',s.title);text('stepSubtitle',s.goal);document.getElementById('guide').innerHTML=`<div><b>Do</b><span>${s.do}</span></div><div><b>Don't</b><span>${s.dont}</span></div><div><b>Done when</b><span>${s.done}</span></div>`;document.getElementById('prevBtn').style.visibility=currentStep===0?'hidden':'visible';document.getElementById('nextBtn').style.visibility=currentStep===steps.length-1?'hidden':'visible';renderWorkspace(s.id)}
function openLog(){hideAll();show('logView');renderLog()}
function openCase(id){if(!state.cases[id])return;state.activeCaseId=id;persist();renderHome()}
function renderLog(){const list=Object.values(state.cases).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));document.getElementById('logList').innerHTML=list.length?list.map(c=>{const done=steps.filter(s=>stepDoneFor(c,s.id)).length;const rev=c.tests.reduce((n,t)=>n+(+t.revenue||0),0);return `<div class="card log-card"><div class="log-title-row"><div><div class="eyebrow">Started ${esc(c.createdAt)} · <span class="case-status ${c.status}">${c.status}</span></div><h3>${esc(c.title)}</h3></div><div class="log-actions"><button class="btn small" onclick="openCase('${c.id}')">Open</button></div></div><p class="log-summary">${esc(c.trend.statement||'Trend not defined yet.')}</p><div class="log-meta"><span class="tag">${done}/9 steps</span><span class="tag">${c.evidence.length} evidence</span><span class="tag">${c.problems.length} problems</span><span class="tag">${c.interviews.length} interviews</span><span class="tag">${c.tests.length} tests</span><span class="tag good">€${rev}</span>${c.review.decision?`<span class="tag">${esc(c.review.decision)}</span>`:''}</div>${c.review.next?`<p class="log-summary"><b>Next:</b> ${esc(c.review.next)}</p>`:''}</div>`}).join(''):'<div class="card empty">No research cases yet.</div>'}
function renderWorkspace(id){const el=document.getElementById('workspace');if(id==='trend')el.innerHTML=trendHTML();if(id==='consequences')el.innerHTML=consequenceHTML();if(id==='actors')el.innerHTML=actorHTML();if(id==='evidence')el.innerHTML=evidenceHTML();if(id==='problems')el.innerHTML=problemsHTML();if(id==='customers')el.innerHTML=customersHTML();if(id==='opportunity')el.innerHTML=opportunityHTML();if(id==='test')el.innerHTML=testHTML();if(id==='decide')el.innerHTML=decideHTML()}
function trendHTML(){const t=C().trend;return `<h3 class="section-title">Describe the structural change</h3><p class="hint">Start with the trend itself, not the business idea.</p><label>Trend statement</label><textarea id="trendStatement" oninput="saveTrend()" placeholder="e.g. AI and cloud growth are accelerating data-center construction in Finland.">${esc(t.statement)}</textarea><div class="row2"><div><label>Signals that it is real</label><textarea id="trendSignals" oninput="saveTrend()" placeholder="Reports, investments, regulation, behavior, statistics...">${esc(t.signals)}</textarea></div><div><label>Why now?</label><textarea id="trendWhy" oninput="saveTrend()" placeholder="What changed recently or is accelerating?">${esc(t.whyNow)}</textarea></div></div>${aiBox('trend')}`}
function consequenceHTML(){return `<h3 class="section-title">Build cause → effect chains</h3><p class="hint">One consequence per row. Go several layers away from the original trend if useful.</p><div class="row2"><div><label>Because...</label><input id="cCause" placeholder="e.g. more data centers"></div><div><label>...this changes</label><input id="cEffect" placeholder="e.g. electricity demand rises"></div></div><label>Why might this matter?</label><input id="cNote" placeholder="Cost, bottleneck, new coordination need..."><button class="btn accent" style="margin-top:10px" onclick="addConsequence()">Add consequence</button>${renderConsequences()}${aiBox('consequences')}`}
function actorHTML(){return `<h3 class="section-title">Who is affected?</h3><p class="hint">Include operators, suppliers, regulators, municipalities, workers, residents, and intermediaries.</p><div class="row2"><div><label>Actor group</label><input id="aName" placeholder="e.g. Finnish municipalities"></div><div><label>How are they affected?</label><input id="aImpact" placeholder="New decision, cost, risk, opportunity, or work?"></div></div><button class="btn accent" style="margin-top:10px" onclick="addActor()">Add actor</button>${renderActors()}${aiBox('actors')}`}
function evidenceHTML(){return `<h3 class="section-title">Evidence inbox</h3><p class="hint">Store raw signals separately from interpretation.</p><div class="callout"><b>Evidence is not an idea.</b><span>Record what happened, what someone said, or what a credible source reports.</span></div><div class="row2"><div><label>Source type</label><select id="eType"><option>Official / report</option><option>News</option><option>Forum / community</option><option>Customer review</option><option>Social media</option><option>Interview / conversation</option><option>Search / keyword</option><option>Competitor</option><option>Marketplace</option><option>Other</option></select></div><div><label>Source / URL / place</label><input id="eSource" placeholder="Fingrid, Reddit, Xiaohongshu..."></div></div><label>What did you observe?</label><textarea id="eText" placeholder="One factual signal per item."></textarea><label>Your interpretation (optional)</label><input id="eNote" placeholder="Keep inference separate from the raw signal."><button class="btn accent" style="margin-top:10px" onclick="addEvidence()">Add evidence</button>${renderEvidence()}${aiBox('evidence')}`}
function problemsHTML(){return `<h3 class="section-title">Turn evidence into problems</h3><p class="hint">Describe friction for a specific actor without embedding the solution.</p><label>Problem statement</label><input id="pStatement" placeholder="e.g. Local contractors cannot see upcoming procurement opportunities early enough."><div class="row3"><div><label>Who has it?</label><input id="pWho"></div><div><label>Evidence</label><input id="pEvidence" placeholder="3 interviews + 5 signals"></div><div><label>Current workaround</label><input id="pWorkaround"></div></div><label>Consequence if unsolved</label><input id="pConsequence"><button class="btn accent" style="margin-top:10px" onclick="addProblem()">Add problem</button>${renderProblems()}${aiBox('problems')}`}
function customersHTML(){return `<h3 class="section-title">Talk to real people</h3><p class="hint">Understand current behavior, not compliments.</p><div class="row2"><div><label>Person / role</label><input id="iPerson"></div><div><label>Date</label><input id="iDate" type="date"></div></div><label>What were they trying to do?</label><input id="iJob"><div class="row2"><div><label>What was difficult?</label><textarea id="iPain"></textarea></div><div><label>What do they do today?</label><textarea id="iCurrent"></textarea></div></div><div class="row2"><div><label>Time / money at stake</label><textarea id="iStake"></textarea></div><div><label>What have they already paid for?</label><textarea id="iSpend"></textarea></div></div><label>Strongest evidence / quote</label><input id="iQuote"><button class="btn accent" style="margin-top:10px" onclick="addInterview()">Add interview</button>${renderInterviews()}${aiBox('customers')}`}
function opportunityHTML(){const h=C().hypothesis;return `<h3 class="section-title">Choose one opportunity</h3><p class="hint">Score the problems, then state one falsifiable hypothesis.</p>${renderRanking()}<hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="row2"><div><label>Customer</label><input id="hCustomer" value="${escAttr(h.customer)}" oninput="saveHypothesis()"></div><div><label>Problem</label><input id="hProblem" value="${escAttr(h.problem)}" oninput="saveHypothesis()"></div><div><label>Current alternative</label><input id="hAlternative" value="${escAttr(h.alternative)}" oninput="saveHypothesis()"></div><div><label>Outcome you might deliver</label><input id="hOutcome" value="${escAttr(h.outcome)}" oninput="saveHypothesis()"></div></div><label>Testable belief</label><textarea id="hBelief" oninput="saveHypothesis()" placeholder="We believe [customer] will pay [price] for [outcome] because [evidence].">${esc(h.belief)}</textarea><div class="row2"><div><label>Success threshold</label><input id="hThreshold" value="${escAttr(h.threshold)}" oninput="saveHypothesis()"></div><div><label>Biggest assumption</label><input id="hAssumption" value="${escAttr(h.assumption)}" oninput="saveHypothesis()"></div></div>${aiBox('opportunity')}`}
function testHTML(){return `<h3 class="section-title">Test behavior before building</h3><p class="hint">Make the smallest manually deliverable offer that tests the core assumption.</p><div class="row2"><div><label>Problem</label><select id="tProblem"><option value="">Choose...</option>${C().problems.map(p=>`<option value="${p.id}">${esc(p.statement)}</option>`).join('')}</select></div><div><label>Price asked (€)</label><input id="tPrice" type="number" min="0"></div></div><label>Offer</label><input id="tOffer" placeholder="What exactly are you asking them to buy or do?"><div class="row3"><div><label>Approached</label><input id="tApproached" type="number" min="0"></div><div><label>Reached buying step</label><input id="tCheckout" type="number" min="0"></div><div><label>Paid</label><input id="tPaid" type="number" min="0"></div></div><label>What happened?</label><textarea id="tResult"></textarea><button class="btn accent" style="margin-top:10px" onclick="addTest()">Log test</button>${renderTests()}${aiBox('test')}`}
function decideHTML(){const r=C().review;return `<h3 class="section-title">Make one decision</h3><p class="hint">Continue only because evidence improved, not because you already invested time.</p><div class="row2"><div><label>Strongest evidence</label><textarea id="rEvidence" oninput="saveReview()">${esc(r.evidence)}</textarea></div><div><label>What surprised you?</label><textarea id="rSurprise" oninput="saveReview()">${esc(r.surprise)}</textarea></div><div><label>What did people actually do/pay for?</label><textarea id="rBehavior" oninput="saveReview()">${esc(r.behavior)}</textarea></div><div><label>What should you NOT build?</label><textarea id="rDontBuild" oninput="saveReview()">${esc(r.dontBuild)}</textarea></div><div><label>What could become a repeatable asset?</label><textarea id="rAsset" oninput="saveReview()">${esc(r.asset)}</textarea></div><div><label>Next move</label><textarea id="rNext" oninput="saveReview()">${esc(r.next)}</textarea></div></div><label>Decision</label><select id="rDecision" onchange="saveReview()"><option value="">Choose...</option>${['Continue','Narrow','Test again','Drop'].map(x=>`<option ${r.decision===x?'selected':''}>${x}</option>`).join('')}</select>${aiBox('decide')}`}
function saveTrend(){C().trend.statement=val('trendStatement');C().trend.signals=val('trendSignals');C().trend.whyNow=val('trendWhy');persist()}
function addConsequence(){const cause=val('cCause').trim(),effect=val('cEffect').trim();if(!cause||!effect)return alert('Add both cause and effect.');C().consequences.push({id:Date.now(),cause,effect,note:val('cNote')});persist();renderStep()}
function addActor(){const name=val('aName').trim(),impact=val('aImpact').trim();if(!name||!impact)return alert('Add actor and impact.');C().actors.push({id:Date.now(),name,impact});persist();renderStep()}
function addEvidence(){const t=val('eText').trim();if(!t)return alert('Add an observation.');C().evidence.push({id:Date.now(),type:val('eType'),source:val('eSource'),text:t,note:val('eNote')});persist();renderStep()}
function addProblem(){const s=val('pStatement').trim();if(!s)return alert('Add a problem statement.');C().problems.push({id:Date.now(),statement:s,who:val('pWho'),evidence:val('pEvidence'),workaround:val('pWorkaround'),consequence:val('pConsequence'),scores:{frequency:0,pain:0,money:0,alternatives:0,reach:0}});persist();renderStep()}
function addInterview(){const person=val('iPerson').trim();if(!person)return alert('Add a person or role.');C().interviews.push({id:Date.now(),person,date:val('iDate'),job:val('iJob'),pain:val('iPain'),current:val('iCurrent'),stake:val('iStake'),spend:val('iSpend'),quote:val('iQuote')});persist();renderStep()}
function totalScore(p){const s=p.scores||{};return ['frequency','pain','money','alternatives','reach'].reduce((n,k)=>n+(+s[k]||0),0)}
function scoreProblem(id,key,value){const p=C().problems.find(x=>x.id===id);if(!p)return;p.scores=p.scores||{};p.scores[key]=+value;persist();renderStep()}
function saveHypothesis(){const h=C().hypothesis;h.customer=val('hCustomer');h.problem=val('hProblem');h.alternative=val('hAlternative');h.outcome=val('hOutcome');h.belief=val('hBelief');h.threshold=val('hThreshold');h.assumption=val('hAssumption');persist()}
function addTest(){const pid=+val('tProblem');if(!pid)return alert('Choose a problem.');const price=+val('tPrice')||0,paid=+val('tPaid')||0;C().tests.push({id:Date.now(),problemId:pid,offer:val('tOffer'),price,approached:+val('tApproached')||0,checkout:+val('tCheckout')||0,paid,result:val('tResult'),revenue:price*paid});persist();renderStep()}
function saveReview(){const r=C().review;r.evidence=val('rEvidence');r.surprise=val('rSurprise');r.behavior=val('rBehavior');r.dontBuild=val('rDontBuild');r.asset=val('rAsset');r.next=val('rNext');r.decision=val('rDecision');persist()}
function remove(kind,id){if(!confirm('Delete this item?'))return;C()[kind]=C()[kind].filter(x=>x.id!==id);persist();renderStep()}
function renderConsequences(){const a=C().consequences;if(!a.length)return '<div class="empty">No consequence chains yet.</div>';return a.map((x,i)=>`<div class="entry"><div class="entry-top"><h4>${i+1}. ${esc(x.cause)} → ${esc(x.effect)}</h4><button class="btn small danger" onclick="remove('consequences',${x.id})">Delete</button></div>${x.note?`<p>${esc(x.note)}</p>`:''}</div>`).join('')}
function renderActors(){const a=C().actors;if(!a.length)return '<div class="empty">No actors mapped yet.</div>';return a.map((x,i)=>`<div class="entry"><div class="entry-top"><h4>${i+1}. ${esc(x.name)}</h4><button class="btn small danger" onclick="remove('actors',${x.id})">Delete</button></div><p>${esc(x.impact)}</p></div>`).join('')}
function renderEvidence(){const a=C().evidence;if(!a.length)return '<div class="empty">No evidence yet.</div>';return a.map((x,i)=>`<div class="entry"><div class="entry-top"><h4>${i+1}. ${esc(x.text)}</h4><button class="btn small danger" onclick="remove('evidence',${x.id})">Delete</button></div><div class="tags"><span class="tag">${esc(x.type)}</span>${x.source?`<span class="tag">${esc(x.source)}</span>`:''}</div>${x.note?`<p>Interpretation: ${esc(x.note)}</p>`:''}</div>`).join('')}
function renderProblems(){const a=C().problems;if(!a.length)return '<div class="empty">No problems yet.</div>';return a.map((x,i)=>`<div class="entry"><div class="entry-top"><h4>${i+1}. ${esc(x.statement)}</h4><button class="btn small danger" onclick="remove('problems',${x.id})">Delete</button></div><p>${x.who?`Who: ${esc(x.who)}\n`:''}${x.evidence?`Evidence: ${esc(x.evidence)}\n`:''}${x.workaround?`Workaround: ${esc(x.workaround)}\n`:''}${x.consequence?`Consequence: ${esc(x.consequence)}`:''}</p>${totalScore(x)?`<div class="tags"><span class="tag good">${totalScore(x)}/25</span></div>`:''}</div>`).join('')}
function renderInterviews(){const a=C().interviews;if(!a.length)return '<div class="empty">No interviews yet.</div>';return a.map((x,i)=>`<div class="entry"><div class="entry-top"><h4>${i+1}. ${esc(x.person)}${x.date?' · '+esc(x.date):''}</h4><button class="btn small danger" onclick="remove('interviews',${x.id})">Delete</button></div><p>Job: ${esc(x.job||'-')}\nPain: ${esc(x.pain||'-')}\nCurrent: ${esc(x.current||'-')}\nStake: ${esc(x.stake||'-')}\nExisting spend: ${esc(x.spend||'-')}${x.quote?'\nQuote: “'+esc(x.quote)+'”':''}</p></div>`).join('')}
function renderRanking(){const a=[...C().problems].sort((x,y)=>totalScore(y)-totalScore(x));if(!a.length)return '<div class="empty">Add evidence-backed problems first.</div>';return a.map(p=>`<div class="entry"><div class="entry-top"><h4>${esc(p.statement)}</h4><span class="tag good">${totalScore(p)}/25</span></div><div class="score-grid">${scoreSelect(p,'frequency','Frequency')}${scoreSelect(p,'pain','Pain')}${scoreSelect(p,'money','Money at stake')}${scoreSelect(p,'alternatives','Poor alternatives')}${scoreSelect(p,'reach','Reachability')}</div></div>`).join('')}
function scoreSelect(p,key,label){const v=(p.scores&&p.scores[key])||0;return `<label>${label}<select onchange="scoreProblem(${p.id},'${key}',this.value)"><option value="0">—</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${v===n?'selected':''}>${n}</option>`).join('')}</select></label>`}
function renderTests(){const a=C().tests;if(!a.length)return '<div class="empty">No validation tests yet.</div>';return a.map((t,i)=>{const p=C().problems.find(x=>x.id===t.problemId);return `<div class="entry"><div class="entry-top"><h4>${i+1}. ${esc(t.offer||'Validation test')}</h4><button class="btn small danger" onclick="remove('tests',${t.id})">Delete</button></div><p>${esc(p?p.statement:'Problem removed')}</p><div class="metric-grid"><div class="metric"><b>${t.approached||0}</b><span>Approached</span></div><div class="metric"><b>${t.checkout||0}</b><span>Buying step</span></div><div class="metric"><b>${t.paid||0}</b><span>Paid</span></div><div class="metric"><b>€${t.revenue||0}</b><span>Revenue</span></div></div>${t.result?`<p>${esc(t.result)}</p>`:''}</div>`}).join('')}
function aiBox(mode){return `<details class="ai" ontoggle="if(this.open)buildPrompt('${mode}')"><summary>Use AI for this step</summary><p class="smallmuted">AI may analyze your material, but it must not invent evidence.</p><textarea id="aiPrompt_${mode}"></textarea><button class="btn small" onclick="copyPrompt('${mode}',event)">Copy prompt</button></details>`}
function buildPrompt(mode){const c=C(),e=c.evidence.map((x,i)=>`${i+1}. [${x.type}] ${x.text}${x.source?` | ${x.source}`:''}`).join('\n')||'(none)',cons=c.consequences.map((x,i)=>`${i+1}. ${x.cause} -> ${x.effect}${x.note?` | ${x.note}`:''}`).join('\n')||'(none)',actors=c.actors.map((x,i)=>`${i+1}. ${x.name}: ${x.impact}`).join('\n')||'(none)',probs=c.problems.map((x,i)=>`${i+1}. ${x.statement} | who: ${x.who||'?'} | evidence: ${x.evidence||'?'} | score: ${totalScore(x)}/25`).join('\n')||'(none)',ints=c.interviews.map((x,i)=>`${i+1}. ${x.person}\nJob: ${x.job||'-'}\nPain: ${x.pain||'-'}\nCurrent: ${x.current||'-'}\nStake: ${x.stake||'-'}\nSpend: ${x.spend||'-'}\nQuote: ${x.quote||'-'}`).join('\n\n')||'(none)';const tasks={trend:'Assess whether this trend is clear and identify what evidence would strengthen or falsify it. Do not suggest products.',consequences:'Extend the consequence map. Separate direct consequences from speculative second-order effects and flag assumptions.',actors:'Identify missing affected actors and explain how each might gain, lose, pay, decide, or receive extra work. Do not choose a customer yet.',evidence:'Cluster the evidence into recurring themes. Separate direct evidence from inference and flag weak or contradictory signals.',problems:'Cluster and rank the problems by evidence strength, pain, frequency, money/time at stake, and poor alternatives. Do not propose products.',customers:'Synthesize interviews. Separate actual behavior from hypothetical statements. Identify repeated pains, workarounds, urgency, and existing spend.',opportunity:'Challenge the opportunity choice and recommend which single problem deserves a validation test based only on the evidence.',test:'Design the smallest real-world validation test. Prefer payment or costly behavior. Define offer, channel, sample size, price, success threshold, and failure threshold.',decide:'Act as a skeptical review board. Recommend Continue, Narrow, Test again, or Drop, and state exactly which evidence supports the decision.'};const h=c.hypothesis;const prompt=`You are helping me run a rigorous business opportunity-discovery process.\n\nCASE: ${c.title}\nTREND: ${c.trend.statement||'(none)'}\nWHY NOW: ${c.trend.whyNow||'(none)'}\n\nCONSEQUENCES:\n${cons}\n\nACTORS:\n${actors}\n\nEVIDENCE:\n${e}\n\nPROBLEMS:\n${probs}\n\nINTERVIEWS:\n${ints}\n\nHYPOTHESIS:\nCustomer: ${h.customer||'-'}\nProblem: ${h.problem||'-'}\nBelief: ${h.belief||'-'}\nThreshold: ${h.threshold||'-'}\n\nRULES:\n- Use only the material above as evidence.\n- Do not invent market demand, customer behavior, willingness to pay, quotes, or facts.\n- Clearly label inference and uncertainty.\n- Prefer real behavior and payment over stated interest.\n\nTASK:\n${tasks[mode]}`;const el=document.getElementById('aiPrompt_'+mode);if(el)el.value=prompt}
async function copyPrompt(mode,event){buildPrompt(mode);const el=document.getElementById('aiPrompt_'+mode);try{await navigator.clipboard.writeText(el.value)}catch(e){el.select();document.execCommand('copy')}const b=event.target;b.textContent='Copied';setTimeout(()=>b.textContent='Copy prompt',900)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='opportunity-lab-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=migrate(JSON.parse(r.result));if(!state.activeCaseId)state.activeCaseId=Object.keys(state.cases)[0];persist();renderHome();alert('Imported.')}catch(err){alert('Could not import file.')}};r.readAsText(f)}
function val(id){return document.getElementById(id)?.value||''}function setVal(id,v){const e=document.getElementById(id);if(e)e.value=v}function text(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(s){return esc(s).replace(/\n/g,' ')}
load();